version: '3.8'
services:
  angular-dev:
    image: node:18
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "if [ ! -d ./node_modules ]; then
        if [ ! -f ./package.json ]; then
          npm install -g @angular/cli &&
          npx ng new my-app --skip-git --directory ./ --force;
        else
          npm install;
        fi
      fi &&
      npx ng serve --host 0.0.0.0"
